# Generated by Django 5.1.4 on 2025-03-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_equipment_supplier_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='effective_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
